### ISSUE TITLE
please don't use node_modules for this

### ISSUE THREAD

**Issue by isaacs** [avajs/find-cache-dir#1]
npm will casually stomp all over node_modules.  It's safest to treat that as its sovereign turf, and never do anything in that folder that isn't specifically and officially related to the management of packages.

I recommend literally any other folder name.  Maybe `.coverage_output/` or something? I don't know.  But please not `node_modules`.  You wouldn't put this stuff in the `.git` folder, it should be treated with a similar level of concern.

**Comment by bcoe** [comment]
@isaacs, I think @jamestalmage was hoping to come to a standard that services such as `AVA`, `tap`, and `nyc` could use for their output, perhaps a better choice would be:

`.cache/ava`.
`.cache/nyc`.
`.cache/tap`.

**Comment by isaacs** [comment]
Ah, right, ok, then `.cache/blerg` makes a lot of sense.

**Comment by jamestalmage** [comment]
I'm fine with whatever makes sense as a standard. 

It started as a top level directory [here](https://github.com/bcoe/nyc/pull/101), but I believe it was @sindresorhus that requested we not add yet another top level directory that people need to `.gitignore` and clutter up the editor tree.

One thing that's really difficult with caching is handling dependency version changes. For instance, there is no good way to (quickly) inspect the full dependency graph of a given Babel preset and create a good hash salt based on that. My hope was, at some point, to ask `npm` to accept the `node_modules/.cache/module-name` as an officially accepted practice, and wipe it out anytime `npm install/update/...` were run.

**Comment by isaacs** [comment]
@jamestalmage If that's what you're after, you don't need a module for that.  Just put the stuff in your module dir rather than in cwd.  `path.join(__dirname, '.cache')` works fine, and will definitely be deleted when npm updates the package.

**Comment by jamestalmage** [comment]
Except that I'm concerned about the complete dependency graph, and potentially Babel plugins I don't even know about. So I want it deleted not just when `ava` is updated, but also when `babel-core`, `babel-plugin-transform-xxx`, or anything else is updated as well.

**Comment by jamestalmage** [comment]
Also,
The advantage to standardizing on a single root directory for all caches (no matter where it's located). Is that you can wipe out all caches with a single predictable command. So if we are running `nyc --cache ava`, then `rm -rf ./.cache` invalidates both of them.

**Comment by sindresorhus** [comment]
What @jamestalmage said. Cache invalidation is hard and especially so when there's a tricky dependency graph involved.

-

> You wouldn't put this stuff in the .git folder

I would, but that wouldn't help in this scenario. And you put your own git hooks in `.git/hooks` anyways.

**Comment by jamestalmage** [comment]
Another reason for `node_modules`:

>  This means users will clear the cache themselves if they trash node_modules and reinstall (even if they don't know the cache is there). If we convince enough modules to adapt that pattern, it also makes trash node_modules/.cache a standard way to clear caches
https://github.com/sindresorhus/ava/pull/352#issuecomment-166673071

Discussion on the difficulties of implementing caching for Babel: https://phabricator.babeljs.io/T6709#67067

**Comment by bcoe** [comment]
I think using `.cache/` could be a pretty good compromise:

* we reduce the amount of cruft at the root level, if you're using `nyc`, `AVA`, `babel`, etc, in conjunction.
* we avoid @isaacs' fears regarding polluting the `node_modules` folder.

I'd happily move `.nyc_output` into the alternative `.cache`.

**Comment by jamestalmage** [comment]
> I think using .cache/ could be a pretty good compromise:

Yeah, I am all for that. I would like to hear what you guys think about some sort of way of automatically clearing that anytime `npm` manipulates the dependencies.

**Comment by isaacs** [comment]
If you want a way to do a thing whenever npm does a thing, that's a request for a lifecycle script or hook.  Make that request over at https://github.com/npm/npm/issues.  It's easy enough to wire up whatever you want without making it have to be a first-class feature of the npm cli.

> And you put your own git hooks in .git/hooks anyways.

That's a documented interface.  I wouldn't presume to add a new folder in `.git/objects/` and expect it to stay were I left it and not cause any problems.

**Comment by sindresorhus** [comment]
> That's a documented interface.

I know I will get a no from this, but would be so nice if there was one folder like .extras that was guaranteed to be untouched in node_modules, where we could put anything, like caching.

**Comment by jamestalmage** [comment]
FYI: https://github.com/npm/npm/issues/11297

**Comment by langri-sha** [comment]
I am having issues with using Yarn. Yarn will wipe out the cache directory on each install. https://github.com/avajs/ava/issues/1436.

Here's a quick way to reproduce:

```
# Change into package directory
cd ~package/
# Use Yarn, get lock file generated
yarn install

# Great! Let's add something
touch node_modules/princess.js
# Force install re-run
yarn install --force
# The princess has left the castle :|
```

**Comment by langri-sha** [comment]
`chokidar` has had `CHOKIDAR_USEPOLLING` and other flags introduced. Because package dependents wouldn't expose these options, it broke the experience for users that, for instance, ran appliances on virtual hosts.

Can this be done in similar fashion here? AVA still simply works, bears no mentions of how to configure the cache, yet us who use a future package manager that aggressively trashes the cache or who share our modules between multiple hosts and worry about multiple tests runners writing to it can still make use of it.
