### ISSUE TITLE
When used with Lerna, a cache directory is created in several different locations

### ISSUE THREAD

**Issue by damienwebdev** [avajs/find-cache-dir#14]
* Operating System: `MacOS v10.14.3`
* Node Version: `v10.15.0`
* NPM Version:`6.7.0`
* Webpack Version: 
```
@angular-devkit/build-angular@0.13.1
  ├── terser-webpack-plugin@1.2.2 
  └─┬ webpack@4.29.0
    └── terser-webpack-plugin@1.2.2  deduped
```

### Expected Behavior
When using lerna for *hoisted* package management in a monorepo, when I do run `lerna run build` and it runs the build script in each of my packages, the resulting cache directory should be in my **root** `node_modules` of my project.

### Actual Behavior
When using lerna for **hoisted** package management, when I do run `lerna run build` and it runs the build script in each of my packages, `ng build` runs webpack with `terser-webpack-plugin` with the [`cache` flag set to true](https://github.com/renovate-bot/angular-cli/blob/bf52b26219ffc16bed2dd55716e21773b415fd2a/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts#L264). This generates a new `node_modules` directory in each of my source directories.

### How Do We Reproduce?

You can reproduce fairly easily by cloning: https://github.com/graycoreio/daffodil and then:

```
npm install -g lerna @angular/cli
lerna run build
look in apps/daffio/ and see a new node_modules folder
```

I was redirected here from https://github.com/webpack-contrib/terser-webpack-plugin/issues/82

**Comment by damienwebdev** [comment]
As a simple solution, what could be done is to check to see if a "node_modules" directory exists in the `cwd` if there isn't one, recursively check up the tree until you hit a "node_modules" directory. This may be dangerous though, so it may make sense to stop at the "project boundary". How `find-cache-dir` determines the project boundary may be difficult though.

**Comment by damienwebdev** [comment]
@sindresorhus could I get a review of this issue, the number of polluting `node_modules` is becoming pretty problematic for me.

**Comment by evocateur** [comment]
This module is working just fine, it doesn't need to be aware of monorepo semantics. If you're using Lerna in "hoisted" mode, you should be running your build from the root, not the leaves. Otherwise, it's on you to configure your webpack plugins' `cache` settings appropriately.
