### ISSUE TITLE
Cache dir returned as undefined if no package.json is present

### ISSUE THREAD

**Issue by erunion** [avajs/find-cache-dir#29]
In a fresh directory, run `npm install find-cache-dir` and then run the following code:

```js
const findCacheDir = require('find-cache-dir');

console.log('directory=', findCacheDir({name: 'unicorns'}))
// directory= undefined
```

Now run `npm init -y` and the above code again:

```
directory= /Users/jon/Desktop/issue-demo/node_modules/.cache/unicorns
```

Ideally, if there's no `package.json` available in the root directory, pulled from `find-up` is should probably default to `os.tmpdir()`?

**Comment by sindresorhus** [comment]
This behavior is documented:

> or undefined if package.json was never found or if the node_modules directory is unwritable.

You can fall back to `os.tmpdir()` yourself. I don't think we can do it by default as users might want to handle it in a different way.

**Comment by erunion** [comment]
Are you open to allowing for `os.tmpdir()` to be passed in as a fallback option? For my particular case, if the cache dir coming back isn't there, I basically have to end up writing my own code to manage the cache directory in `os.tmpdir()`. Would be nice if the module could just handle it all for me.

**Comment by sindresorhus** [comment]
I guess we could have a `fallBackToTempDirectory` kinda option that would make it use `os.tmpdir()` if "package.json was never found or if the node_modules directory is unwritable". The option needs a better name though.
