### ISSUE TITLE
Allow for configuring the cache dir

### ISSUE THREAD

**Issue by deiga** [avajs/find-cache-dir#9]
It would be great if I could set f.ex. `NODE_CACHE_ROOT=/tmp`

**Comment by sindresorhus** [comment]
There are lots of more generic cache modules on npm. This one is specifically made to store it in the current location.

**Comment by deiga** [comment]
@sindresorhus That answer is kind of unhelpful, since I can't control which of my dependencies use this module. Which in turn means I have no control over where files are stored.
